#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="sudo shutdown -h now" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="sudo pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	tt="taskwarrior-tui" \
	ttc="taskwarrior-tui -r completed" \
	tts="task timesheet" \
	K="klick -P -i -s 3" \
	z="zathura"

alias \
	magit="nvim -c MagitOnly" \
	tlmgr="/usr/share/texmf-dist/scripts/texlive/tlmgr.pl --usermode" \
	vw="nvim $HOME/Documentos/vimwiki/index.md" \
	dia="nvim $HOME/Documentos/vimwiki/diary/$(date "+%Y-%m-%d" | sed -e "s/$/.md/")" \
	plan="nvim $HOME/Documentos/vimwiki/diary/$(date -d tomorrow "+%Y-%m-%d" | sed -e "s/$/.md/")" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/zshnameddirrc" \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \
	tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf" \
	yta='youtube-dl -x --audio-format mp3 -f bestaudio -o "%(title)s.%(ext)s" --add-metadata'\
	yt='ytfzf -t'\
	bca='mpv --start=0:00 ~/Documentos/Biblioteca/Idiomas/chino/defrancis\ audio/b/bc4.mp3'\
	bcra='mpv --start=3:15 ~/Documentos/Biblioteca/Idiomas/chino/defrancis\ audio/b/bcr01.mp3'\
	b='echo -e "enter brightness:\n"; read val; xrandr  --output HDMI2 --brightness "${val}"'\
	Pg="rsync -rtvzP --delete ~/.local/share/pg/ cipriano.es:/var/www/cipriano"\
	Jpc="rsync -aP ~/pg/ root@192.168.1.140:/var/www/cipriano/"\
	bib="nvim $BIB"\
	wpj='wol 00:26:22:f0:24:9b'\
	scio='zathura ~/Documentos/Biblioteca/Religión/labibliavulgatal01scio.djvu'\
	aadz='zathura ~/Documentos/Biblioteca/Filosofía/aadz/Nietzsche\ Friedrich\ -\ Also\ Sprach\ Zarathustra.pdf & st -e nvim ~/Documentos/Biblioteca/Filosofía/aadz/aadz.tex &'\
	cdp='cd /home/runiales/Documentos/Estudios/Facultad/maes/prácticas/ && nvim Cipriano_cuaderno.tex'\
	tfm='cd /home/runiales/Documentos/Estudios/Facultad/maes/tfm/ && nvim cipriano_tfm.tex'\
	pfm='cd /home/runiales/Documentos/Facultad/Máster/Segundo_Semestre/TFM/presentación && nvim b.tex'\
	fb='B && z "$(fzf)"'\
	T='nvim "$(find /home/runiales/Documentos/Trabajo/Oposiciones/temas | grep tex | fzf)"'\
	llat='zathura ${XDG_DOCUMENTS_DIR:-$HOME/Documentos}/Biblioteca/Lantiguas/latín/lingualat.pdf'
